[project]
name = "living-book-backend"
version = "0.1.0"
dependencies = [
    "fastapi[standard]",
    "qdrant-client",
    "google-generativeai",
    "uvicorn",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.uv]
requires-python = ">=3.12"
